# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tes (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tes (iOS)
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'

end

target 'tes (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tes (macOS)
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'

end
